<?php

namespace white\commerce\sendcloud\models;

use craft\helpers\ArrayHelper;
use InvalidArgumentException;
use yii\base\Arrayable;
use yii\base\ArrayableTrait;

class ParcelItem implements Arrayable
{
    use ArrayableTrait {
        toArray as traitToArray;
    }
    /**
     * @param string|null $hsCode [Harmonized System Code](https://en.wikipedia.org/wiki/Harmonized_System). Providing a complete HS code with more characters increases the delivery rate.
     * @param string $weight Weight of a single item in kilograms.
     * @param int $quantity Quantity of items shipped.
     * @param string $description Description of the item.
     * @param string|null $originCountry [ISO-2 code](http://www.nationsonline.org/oneworld/country_code_list.htm) of the country where the items were originally produced.
     * @param float $value Value of a single item.
     * @param string|null $sku The SKU of the product.
     * @param string|null $productId The internal ID of the product.
     * @param array $properties The list of properties of the product. Used as a JSON object with {‘key’: ‘value’}.
     * @param string|null $itemId External ID of the item generated by a shop system or similar.
     * @param string|null $returnReason The return reason identifier matching the ones provided from Sendcloud. Only applicable for returns.
     * @param string|null $returnMessage Optional a message relating to the return. Only applicable for returns.
     * @param string|null $midCode Code to identify the manufacturer of the product. It is required when shipping to the US and is used for generating commercial invoice.
     * @param string|null $materialContent Composition of the items. Used for commercial invoice generation.
     * @param string|null $intendedUse Text that identifies the Intended Use of the item. This will be used to classify the item based on the new ICS2 system. Used for commercial invoice generation.
     */
    public function __construct(
        protected ?string $hsCode = null,
        protected string $weight,
        protected int $quantity,
        protected string $description,
        protected ?string $originCountry = null,
        protected float $value,
        protected ?string $sku = null,
        protected ?string $productId = null,
        protected array $properties = [],
        protected ?string $itemId = null,
        protected ?string $returnReason = null,
        protected ?string $returnMessage = null,
        protected ?string $midCode = null,
        protected ?string $materialContent = null,
        protected ?string $intendedUse = null,
    ){
    }

    public function getHsCode(): ?string
    {
        return $this->hsCode;
    }

    public function setHsCode(?string $hsCode): void
    {
        $this->hsCode = $hsCode;
    }

    public function getWeight(): string
    {
        return $this->weight;
    }

    public function setWeight(string $weight): void
    {
        $this->weight = number_format($weight, 3);
    }

    public function getQuantity(): int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): void
    {
        $this->quantity = $quantity;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    public function getOriginCountry(): ?string
    {
        return $this->originCountry;
    }

    public function setOriginCountry(?string $originCountry): void
    {
        $this->originCountry = $originCountry;
    }

    public function getValue(): float
    {
        return $this->value;
    }

    public function setValue(float $value): void
    {
        $this->value = $value;
    }

    public function getSku(): ?string
    {
        return $this->sku;
    }

    public function setSku(?string $sku): void
    {
        $this->sku = $sku;
    }

    public function getProductId(): ?string
    {
        return $this->productId;
    }

    public function setProductId(?string $productId): void
    {
        $this->productId = $productId;
    }

    public function getProperties(): array
    {
        return $this->properties;
    }

    public function setProperties(array $properties): void
    {
        $this->properties = $properties;
    }

    public function getItemId(): ?string
    {
        return $this->itemId;
    }

    public function setItemId(?string $itemId): void
    {
        $this->itemId = $itemId;
    }

    public function getReturnReason(): ?string
    {
        return $this->returnReason;
    }

    public function setReturnReason(?string $returnReason): void
    {
        $this->returnReason = $returnReason;
    }

    public function getReturnMessage(): ?string
    {
        return $this->returnMessage;
    }

    public function setReturnMessage(?string $returnMessage): void
    {
        $this->returnMessage = $returnMessage;
    }

    public function getMidCode(): ?string
    {
        return $this->midCode;
    }

    public function setMidCode(?string $midCode): void
    {
        $this->midCode = $midCode;
    }

    public function getMaterialContent(): ?string
    {
        return $this->materialContent;
    }

    public function setMaterialContent(?string $materialContent): void
    {
        $this->materialContent = $materialContent;
    }

    public function getIntendedUse(): ?string
    {
        return $this->intendedUse;
    }

    public function setIntendedUse(?string $intendedUse): void
    {
        $this->intendedUse = $intendedUse;
    }

    public function fields(): array
    {
        return [
            'description',
            'quantity',
            'weight',
            'value',
            'sku',
        ];
    }

    public function extraFields(): array
    {
        return [
            'hsCode',
            'originCountry',
            'productId',
            'properties',
            'itemId',
            'returnReason',
            'returnMessage',
            'midCode',
            'materialContent',
            'intendedUse',
        ];
    }
}
